# Capstone Project

TMDB Dataset found at:
https://www.kaggle.com/tmdb/tmdb-movie-metadata

This Dataset from The Movie Database contains information on over 14,000 films.  Features include numeric variables like budget and revenue, as well as categorical variables like genres and language.

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
%matplotlib inline

In [2]:
movies = pd.read_csv('~/Desktop/Data_Science/tmdb/tmdb_5000_movies.csv')

In [3]:
import ast

def ExtractGenreAsList(dictionary_genre):
    dictionary_genre = ast.literal_eval(dictionary_genre)
    list_genres = []
    for entry in dictionary_genre:
        list_genres.append(entry['name'])
    return list_genres

In [5]:
movies["genre_list"] = movies["genres"].apply(ExtractGenreAsList)

In [6]:
unique_genres = []
for row in movies["genre_list"]:
    for genres in row:
        unique_genres.append(genres)

unique_genres = set(unique_genres)

print(unique_genres)

{'Action', 'Crime', 'Family', 'Mystery', 'Thriller', 'Music', 'Foreign', 'War', 'Adventure', 'Comedy', 'Romance', 'Horror', 'Western', 'History', 'Fantasy', 'TV Movie', 'Documentary', 'Drama', 'Animation', 'Science Fiction'}

In [7]:
def GetGenrePerRow(row, genre):
    if genre in row:
        return 1
    else:
        return 0

In [8]:
for genre in unique_genres:
    movies[genre] = movies["genre_list"].apply(lambda x: GetGenrePerRow(x, genre))

In [9]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,Romance,Horror,Western,History,Fantasy,TV Movie,Documentary,Drama,Animation,Science Fiction
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,0,0,0,0,1,0,0,0,0,1
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,0,0,0,0,1,0,0,0,0,0
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,0,0,0,0,0,0,0,0,0,0
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,0,0,0,0,0,0,0,1,0,0
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,0,0,0,0,0,0,0,0,0,1

In [16]:
movies.drop(['homepage', 'id', 'overview'], axis=1)

,budget,genres,keywords,original_language,original_title,popularity,production_companies,production_countries,release_date,revenue,...,Romance,Horror,Western,History,Fantasy,TV Movie,Documentary,Drama,Animation,Science Fiction
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,...,0,0,0,0,1,0,0,0,0,1
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,...,0,0,0,0,1,0,0,0,0,0
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,...,0,0,0,0,0,0,0,0,0,0
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,...,0,0,0,0,0,0,0,1,0,0
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,...,0,0,0,0,0,0,0,0,0,1
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,...,0,0,0,0,1,0,0,0,0,0
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...","[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,...,0,0,0,0,0,0,0,0,1,0
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,...,0,0,0,0,0,0,0,0,0,1
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,...,0,0,0,0,1,0,0,0,0,0
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,...,0,0,0,0,1,0,0,0,0,0
10,270000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Superman Returns,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-06-28,391081192,...,0,0,0,0,1,0,0,0,0,1
11,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",en,Quantum of Solace,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2008-10-30,586090727,...,0,0,0,0,0,0,0,0,0,0
12,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",en,Pirates of the Caribbean: Dead Man's Chest,145.847379,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""JM"", ""name"": ""Jamaica""}, {""is...",2006-06-20,1065659812,...,0,0,0,0,1,0,0,0,0,0
13,255000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",en,The Lone Ranger,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-07-03,89289910,...,0,0,1,0,0,0,0,0,0,0
14,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Man of Steel,99.398009,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2013-06-12,662845518,...,0,0,0,0,1,0,0,0,0,1
15,225000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,The Chronicles of Narnia: Prince Caspian,53.978602,"[{""name"": ""Walt Disney"", ""id"": 5888}, {""name"":...","[{""iso_3166_1"": ""CZ"", ""name"": ""Czech Republic""...",2008-05-15,419651413,...,0,0,0,0,1,0,0,0,0,0
16,220000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...","[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",en,The Avengers,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-04-25,1519557910,...,0,0,0,0,0,0,0,0,0,1
17,380000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",en,Pirates of the Caribbean: On Stranger Tides,135.413856,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-05-14,1045713802,...,0,0,0,0,1,0,0,0,0,0
18,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...","[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",en,Men in Black 3,52.035179,"[{""name"": ""Amblin Entertainment"", ""id"": 56}, {...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-23,624026776,...,0,0,0,0,0,0,0,0,0,1
19,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",en,The Hobbit: The Battle of the Five Armies,120.965743,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2014-12-10,956019788,...,0,0,0,0,1,0,0,0,0,0
20,215000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1872, ""name"": ""loss of father""}, {""id""...",en,The Amazing Spider-Man,89.866276,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-06-27,752215857,...,0,0,0,0,1,0,0,0,0,0
21,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 4147, ""name"": ""robin hood""}, {""id"": 43...",en,Robin Hood,37.668301,"[{""name"": ""Imagine Entertainment"", ""id"": 23}, ...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2010-05-12,310669540,...,0,0,0,0,0,0,0,0,0,0
22,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 603, ""name"": ""elves""}, {""id"": 604, ""na...",en,The Hobbit: The Desolation of Smaug,94.370564,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2013-12-11,958400000,...,0,0,0,0,1,0,0,0,0,0
23,180000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 392, ""name"": ""england""}, {""id"": 1461, ...",en,The Golden Compass,42.990906,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2007-12-04,372234864,...,0,0,0,0,1,0,0,0,0,0
24,207000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...","[{""id"": 774, ""name"": ""film business""}, {""id"": ...",en,King Kong,61.226010,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2005-12-14,550000000,...,0,0,0,0,0,0,0,1,0,0
25,200000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...","[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",en,Titanic,100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1997-11-18,1845034188,...,1,0,0,0,0,0,0,1,0,0
26,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 393, ""name"": ""civil war""}, {""id"": 6091...",en,Captain America: Civil War,198.372395,"[{""name"": ""Studio Babelsberg"", ""id"": 264}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-04-27,1153304495,...,0,0,0,0,0,0,0,0,0,1
27,209000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 28, ""n...","[{""id"": 1721, ""name"": ""fight""}, {""id"": 4410, ""...",en,Battleship,64.928382,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-04-11,303025485,...,0,0,0,0,0,0,0,0,0,1
28,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-06-09,1513528810,...,0,0,0,0,0,0,0,0,0,1
29,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 4289, ""nam...",en,Skyfall,93.004993,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2012-10-25,1108561013,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4773,27000,"[{""id"": 35, ""name"": ""Comedy""}]","[{""id"": 1361, ""name"": ""salesclerk""}, {""id"": 30...",en,Clerks,19.748658,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1994-09-13,3151130,...,0,0,0,0,0,0,0,0,0,0
4774,27000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...","[{""id"": 1566, ""name"": ""dream""}, {""id"": 13059, ...",en,Pink Narcissus,0.027811,"[{""name"": ""Strand Releasing"", ""id"": 3923}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1971-01-01,0,...,1,0,0,0,0,0,0,1,0,0
4775,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...","[{""id"": 171993, ""name"": ""mumblecore""}]",en,Funny Ha Ha,0.362633,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2002-09-20,76901,...,0,0,0,0,0,0,0,1,0,0
4776,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 1438, ""name"": ""office""}, {""id"": 9673, ...",en,In the Company of Men,2.634007,"[{""name"": ""Alliance Atlantis Communications"", ...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",1997-01-19,0,...,0,0,0,0,0,0,0,1,0,0
4777,0,"[{""id"": 18, ""name"": ""Drama""}]",[],en,Manito,0.039264,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2002-01-15,0,...,0,0,0,0,0,0,0,1,0,0
4778,0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...","[{""id"": 10022, ""name"": ""rampage""}, {""id"": 1454...",en,Rampage,7.101197,"[{""name"": ""Boll Kino Beteiligungs GmbH & Co. K...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",2009-08-14,0,...,0,0,0,0,0,0,0,1,0,0
4779,0,"[{""id"": 35, ""name"": ""Comedy""}]","[{""id"": 305, ""name"": ""moon""}, {""id"": 490, ""nam...",en,Slacker,3.320622,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1990-07-27,0,...,0,0,0,0,0,0,0,0,0,0
4780,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 80, ""n...",[],en,Dutch Kills,0.038143,[],[],2015-10-02,0,...,0,0,0,0,0,0,0,1,0,0
4781,22000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 13043, ""name"": ""dating""}, {""id"": 15160...",en,Dry Spell,0.048948,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-02-14,0,...,1,0,0,0,0,0,0,0,0,0
4782,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10751, ""n...","[{""id"": 186, ""name"": ""christianity""}, {""id"": 4...",en,Flywheel,1.048524,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2003-01-01,0,...,0,0,0,0,0,0,0,1,0,0
4783,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...","[{""id"": 9712, ""name"": ""possession""}]",en,Backmask,3.619167,"[{""name"": ""GO Productions"", ""id"": 2943}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-01-16,0,...,0,1,0,0,0,0,0,0,0,0
4784,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...","[{""id"": 171993, ""name"": ""mumblecore""}]",en,The Puffy Chair,1.243955,[],[],2005-01-17,0,...,1,0,0,0,0,0,0,1,0,0
4785,0,"[{""id"": 18, ""name"": ""Drama""}]",[],en,Stories of Our Lives,0.327794,[],"[{""iso_3166_1"": ""KE"", ""name"": ""Kenya""}]",2014-09-05,0,...,0,0,0,0,0,0,0,1,0,0
4786,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 10183, ""name"": ""independent film""}]",en,Breaking Upwards,0.674570,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-03-14,0,...,1,0,0,0,0,0,0,0,0,0
4787,0,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...","[{""id"": 9715, ""name"": ""superhero""}]",en,All Superheroes Must Die,3.545991,"[{""name"": ""Grindfest"", ""id"": 18818}]",[],2011-10-26,0,...,0,0,0,0,0,0,0,0,0,1
4788,12000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 35, ""nam...","[{""id"": 237, ""name"": ""gay""}, {""id"": 900, ""name...",en,Pink Flamingos,4.553644,"[{""name"": ""Dreamland Productions"", ""id"": 407}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1972-03-12,6000000,...,0,1,0,0,0,0,0,0,0,0
4789,0,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 6782, ""name"": ""addiction""}, {""id"": 155...",en,Clean,1.464566,[],"[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2004-09-01,0,...,0,0,0,0,0,0,0,1,0,0
4790,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10769, ""n...",[],fa,دایره,1.193779,"[{""name"": ""Jafar Panahi Film Productions"", ""id...","[{""iso_3166_1"": ""IR"", ""name"": ""Iran""}]",2000-09-08,0,...,0,0,0,0,0,0,0,1,0,0
4791,13,"[{""id"": 27, ""name"": ""Horror""}]","[{""id"": 14903, ""name"": ""home invasion""}]",en,Tin Can Man,0.332679,"[{""name"": ""Park Films"", ""id"": 21871}, {""name"":...","[{""iso_3166_1"": ""IE"", ""name"": ""Ireland""}]",2007-01-01,0,...,0,1,0,0,0,0,0,0,0,0
4792,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...","[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",ja,キュア,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-11-06,99000,...,0,1,0,0,0,0,0,0,0,0
4793,0,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 718, ""name"": ""confession""}, {""id"": 100...",en,On The Downlow,0.029757,"[{""name"": ""Iconoclast Films"", ""id"": 26677}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-04-11,0,...,0,0,0,0,0,0,0,1,0,0
4794,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...",[],en,Sanctuary: Quite a Conundrum,0.166513,"[{""name"": ""Gold Lion Films"", ""id"": 37870}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-01-20,0,...,0,1,0,0,0,0,0,0,0,0
4795,0,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 10726, ""name"": ""gang""}, {""id"": 33928, ...",en,Bang,0.918116,"[{""name"": ""Asylum Films"", ""id"": 10571}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-09-09,0,...,0,0,0,0,0,0,0,1,0,0
4796,7000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...","[{""id"": 1448, ""name"": ""distrust""}, {""id"": 2101...",en,Primer,23.307949,"[{""name"": ""Thinkfilm"", ""id"": 446}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-10-08,424760,...,0,0,0,0,0,0,0,1,0,1
4797,0,"[{""id"": 10769, ""name"": ""Foreign""}, {""id"": 53, ...",[],en,Cavite,0.022173,[],[],2005-03-12,0,...,0,0,0,0,0,0,0,0,0,0
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,...,0,0,0,0,0,0,0,0,0,0
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],en,Newlyweds,0.642552,[],[],2011-12-26,0,...,1,0,0,0,0,0,0,0,0,0
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,...,1,0,0,0,0,1,0,1,0,0
4801,0,[],[],en,Shanghai Calling,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,...,0,0,0,0,0,0,0,0,0,0
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,...,0,0,0,0,0,0,1,0,0,0

## Question 1: Is one genre more popular than another?

In [14]:
movies['Action', 'Crime', 'Family', 'Mystery', 'Thriller', 'Music', 'Foreign', 'War', 'Adventure', 'Comedy', 'Romance', 'Horror', 'Western', 'History', 'Fantasy', 'TV Movie', 'Documentary', 'Drama', 'Animation', 'Science Fiction'].describe()

KeyError: ('Action', 'Crime', 'Family', 'Mystery', 'Thriller', 'Music', 'Foreign', 'War', 'Adventure', 'Comedy', 'Romance', 'Horror', 'Western', 'History', 'Fantasy', 'TV Movie', 'Documentary', 'Drama', 'Animation', 'Science Fiction')

In [11]:
for genre in unique_genres:
    movies[genre].boxplot()

AttributeError: 'Series' object has no attribute 'boxplot'

In [10]:
movies[genres in unique_genres].boxplot(by='release_year', figsize=(10,20))
plt.xticks(rotation = 90)

KeyError: True